"""add_users_and_profiles

Revision ID: b91cd45c563c
Revises: 
Create Date: 2025-12-18 22:58:51.946104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91cd45c563c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('height_text', sa.String(length=20), nullable=False),
    sa.Column('weight_lbs', sa.Integer(), nullable=False),
    sa.Column('goal_weight_lbs', sa.Integer(), nullable=False),
    sa.Column('is_male', sa.Boolean(), nullable=False),
    sa.Column('activity_level_index', sa.Integer(), nullable=False),
    sa.Column('goal_type_index', sa.Integer(), nullable=False),
    sa.Column('calories_target', sa.Integer(), nullable=False),
    sa.Column('protein_target', sa.Integer(), nullable=False),
    sa.Column('carbs_target', sa.Integer(), nullable=False),
    sa.Column('fat_target', sa.Integer(), nullable=False),
    sa.Column('selected_vitamins', sa.Text(), nullable=False),
    sa.Column('dietary_restrictions', sa.Text(), nullable=False),
    sa.Column('disliked_foods', sa.Text(), nullable=False),
    sa.Column('selected_dining_halls', sa.Text(), nullable=False),
    sa.Column('delivery_method_index', sa.Integer(), nullable=False),
    sa.Column('appearance_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

